version: '2'

services:
  dbos:
    image: mysql:5.7
    volumes:
      - mysql_storage:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass123
      MYSQL_USER: manish
      MYSQL_PASSWORD: pass123
      MYSQL_DATABASE: mydb


  wpos:
    image: wordpress:5.1.1-php7.3-apache
    volumes:
      - wp_storage:/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: dbos
      WORDPRESS_DB_USER: manish
      WORDPRESS_DB_PASSWORD: pass123
      WORDPRESS_DB_NAME: mydb
    ports:
      - 8081:80
    depends_on:
      - dbos

volumes:
  wp_storage:
  mysql_storage:
